const partialautomaticdata = {
  currentDate: "February 15, 2022",
  FEMAAwardNumber: "FEMA-4609-DR-TN",
  PAID: "PA ID# 125-15160-00",
  applicantLegalName: "City of Waverly",
  formOfAddress: "The Honorable",
  contact: "Joe Pitts",
  title: "Mayor",
  streetAddress: "1 Public Square, 4th Floor",
  city: "Clarksville",
  state: "TN",
  zipCode: "37040",
  totalAmount: "$57,656.51",
  federalShare: "$$54,621.96",
  stateShare: "$3,034.55",
  dateFederalPaid: "12/01/2021",
  dateStatePaid: "12/01/2021",
  federalReferenceNumber: "4888605",
  stateReferenceNumber: "4888605",
  financialOfficeContactName: "Sharon Way",
  financialOfficeContactTitle: "Public Assistance Financial Officer",
  financialOfficeContactNumber: "(615) 741-0556",
  financialOfficeContactEmail: "Sharon.Way@tn.gov",
  liasonTitle: "Public Assistance Specialist",
  liasonContactName: "Kelly Jo Dyer",
  liasonContactNumber: "(615) 741-3753",
  liasonContactEmail: "Kelly.Jo.Dyer@tn.gov",
  PAManagerName: "Judith L. Huff",
  PAManagerTitle: "Public Assistance Manager",
  PAInitials: "JLH",
  financialOfficerInitials: "sdw",
  county: "Montgomery County",
  TEMARegion: "Middle Tennessee",
};

export default partialautomaticdata;
