const p4_to_fema = {
  director_contact_first_name: "John",
  director_contact_last_name: "Doe",
  director_contact_title: "Director",
  adjutant_contact_form_of_address: "Major General",
  adjutant_contact_first_name: "Paul",
  adjutant_contact_last_name: "Smith",
  adjutant_contact_title: "The Adjudant General",
  current_date: "May 15, 2021",
  disaster_number: "1909",
  fips_number: "123456",
  applicant_legal_name: "City of Waverly",
  fema_contact_form_of_address: "The Honorable",
  fema_contact_first_name: "Shirley",
  fema_contact_last_name: "Jackson",
  fema_contact_title: "Director",
  fema_contact_location_name: "Location Name",
  fema_contact_location_line_1: "46 Main Street East",
  fema_contact_city: "Knoxville",
  fema_contact_state: "Tennessee",
  fema_contact_zip_code: "37901",
  fema_contact_name_prefix: "Ms.",
  program_manager_first_name: "Laura",
  program_manager_last_name: "Carter",
  program_manager_phone_business: "(425) 555-0123",
  program_manager_phone_email: "lcarter@gmail.com",
  alternate_gars_first_name: "David",
  alternate_gars_last_name: "Roberts",
  alternate_gars_title: "Regional Manager",
  alternate_gars_initials: "D.R.",
  pa_liaison_initials: "L.R.",
  applicant_county: "Knox County",
  tema_region: "East Region",
};

export default p4_to_fema;
